-- Wipe and reseed items with full binfluencer personality
delete from bindicator_items;

-- Items are written once and copied across all 5 councils. Bin types follow each
-- council's naming convention (general/recycling/garden) — we'll handle exceptions
-- later if a council differs.

with items(item_name, bin_type, category, notes, tip, fun_fact) as (values
  -- THE TRICKY KITCHEN
  ('Pizza box', 'general', 'tricky',
    'Greasy lid? General. Clean lid? Recycling.',
    'Tear the box in half. The greasy bottom goes in general. The clean lid goes in recycling.',
    'One greasy pizza box can contaminate an entire batch of recycling. The pizza box is genuinely the most controversial bin item in the country.'),
  ('Tea bag', 'general', 'food',
    'Most tea bags contain a tiny bit of plastic.',
    'PG Tips, Yorkshire and Twinings have all moved to plastic-free, but most other brands still aren''t fully compostable.',
    'A typical tea bag contains around 0.7g of plastic. The British drink 100 million cups of tea a day. Do the maths.'),
  ('Coffee pod (aluminium)', 'recycling', 'tricky',
    'Empty it first. Aluminium pods are recyclable, plastic ones often aren''t.',
    'Pop the used grounds into your garden bin or compost, then put the empty pod in recycling.',
    'Nespresso runs a free pod recycling service via Royal Mail. They will literally come and get them.'),
  ('Coffee cup (takeaway)', 'general', 'tricky',
    'The plastic lining means most go in general waste.',
    'Costa, Pret and Greggs run in-store cup recycling. The bin you put it in matters less than the cup you bought.',
    'The UK chucks 2.5 billion takeaway coffee cups a year. Bringing your own gets you 25p off at most chains.'),
  ('Banana skin', 'garden', 'food',
    'Garden waste bin if your council collects food. Otherwise general.',
    'Compost it if you can — banana skins are practically nutritional fairy dust for tomatoes.',
    'A banana skin takes 2 years to decompose in landfill. In compost, about 4 weeks.'),
  ('Egg shells', 'garden', 'food',
    'Garden waste or compost. Wash them first if you''re feeling fancy.',
    'Crush them up — they break down faster and slugs hate crawling over the sharp edges.',
    'Egg shells are 95% calcium carbonate, the same stuff as antacid tablets. Bins love them.'),
  ('Cooking oil', 'general', 'food',
    'NEVER down the sink. Cool it, bottle it, bin it.',
    'Pour it back into the original bottle once it''s cooled. Some councils have oil banks. Most just want it sealed.',
    'Fatbergs are real. The Whitechapel Fatberg in 2017 was 250 metres long and weighed 130 tonnes.'),
  ('Bones', 'general', 'food',
    'Cooked bones go in general waste. Garden bin people, avert your eyes.',
    'Wrap them so they don''t leak. Your bin lorry friends will thank you.',
    'Bones can take centuries to decompose. The triceratops fossil hasn''t. Yet.'),

  -- PLASTIC PURGATORY
  ('Plastic bottle', 'recycling', 'plastic',
    'Always rinse and squash. Lid back on.',
    'Squashing a bottle saves about a third of bin space. The lid stays attached so it survives the sorting machines.',
    'A plastic bottle takes 450 years to decompose. Glass takes a million. Cheery.'),
  ('Plastic bag', 'general', 'plastic',
    'Most can''t go in your home recycling bin.',
    'Tesco, Sainsbury''s and most big supermarkets have plastic bag recycling at the door. Save them up and take them with you.',
    'The 5p bag charge cut plastic bag use by 95% almost overnight. Behavioural economics works.'),
  ('Cling film', 'general', 'plastic',
    'It''s recyclable in theory, not in your kerbside bin.',
    'Same drill as plastic bags — supermarket front-of-store recycling.',
    'The first cling film was invented by accident in 1933 when a chemist tried to make a hairspray bottle.'),
  ('Yoghurt pot', 'recycling', 'plastic',
    'Rinse it. Foil lid removed. Pot in.',
    'Most pots are PP (polypropylene, code 5) which is widely recycled. The foil lid usually isn''t.',
    'Müller alone makes 1.4 billion yoghurts a year in the UK. That''s a lot of pots.'),
  ('Plastic film tray (ready meal)', 'recycling', 'plastic',
    'Black plastic is the controversial one. Most sorting machines can''t see it.',
    'If it''s black, check the council guidance. Coloured trays are usually fine.',
    'Sorting machines use infrared to identify plastics. Black plastic absorbs the light, so the machine sees nothing and sends it to general.'),
  ('Bubble wrap', 'general', 'plastic',
    'Same as plastic bags — supermarket front-of-store recycling.',
    'Pop it first. We won''t tell anyone.',
    'Bubble wrap was originally invented in 1957 as 3D wallpaper. It flopped. The packaging revolution came later.'),

  -- PAPER & CARDBOARD
  ('Cardboard', 'recycling', 'paper',
    'Flatten it. Take the tape off if you can be bothered.',
    'Big boxes hide bin-day capacity. Always flatten.',
    'Recycling 1 tonne of cardboard saves about 17 trees and 4,000 kWh of electricity.'),
  ('Wrapping paper', 'general', 'paper',
    'Glittery, foily, plasticky? General. Plain? Recycling.',
    'The scrunch test. If it stays scrunched, it''s recyclable. If it springs back, it''s not.',
    'Britain throws away 227,000 miles of wrapping paper every Christmas. Enough to wrap around the equator nine times.'),
  ('Newspaper', 'recycling', 'paper',
    'Straight in the recycling, no fuss.',
    'Don''t bag it. Loose paper is happier paper.',
    'Newspapers are typically made from a mix of fresh and recycled fibres. The same sheet can be recycled about 7 times before the fibres get too short.'),
  ('Greetings card', 'recycling', 'paper',
    'Plain card recycles. Glittery / musical / felt-covered ones don''t.',
    'If it sings when you open it, it has a battery. Take that out first.',
    'A card with glitter is so contaminated it can''t be recycled. The glitter spreads through every other piece of paper in the load.'),
  ('Receipt', 'general', 'paper',
    'Thermal receipts contain BPA and can''t be recycled.',
    'Ask for a digital receipt where you can. Tiny act, mildly heroic.',
    'Receipts contain a chemical called bisphenol A which is harmful in recycling. Just bin them.'),

  -- GLASS & METAL
  ('Glass bottle', 'recycling', 'glass',
    'Rinse it. Lid off (lid is metal, that''s recycling too).',
    'Take broken glass to a bottle bank rather than your kerbside bin to keep bin crews safe.',
    'Glass can be recycled infinitely. The same molecule could have been a Roman wine bottle and is now your IPA.'),
  ('Drinks can', 'recycling', 'metal',
    'Squash if you can. Rinse if it''s sticky.',
    'A drinks can recycled today is back on the shelf as a new can in 60 days.',
    'It takes 95% less energy to recycle aluminium than to make new. Recycling one can saves enough energy to power a TV for 3 hours.'),
  ('Tin can (food)', 'recycling', 'metal',
    'Rinse it out. Leave the lid attached if you can.',
    'Soup, beans, dog food — all the same drill. Steel cans are 100% recyclable.',
    'Steel is the most recycled material on Earth by weight. More than paper, plastic, glass and aluminium combined.'),
  ('Aerosol can', 'recycling', 'metal',
    'Empty cans only. Don''t squash, don''t pierce.',
    'If it still hisses, it''s not empty. Use it up first.',
    'Aerosols haven''t contained ozone-damaging CFCs since the late 1980s. The hole is healing nicely.'),
  ('Foil (kitchen)', 'recycling', 'metal',
    'Scrunch test it — if it stays scrunched, it''s aluminium. Recycle.',
    'Group small bits of foil together into a tennis-ball-sized clump so the sorters can spot it.',
    'A single piece of foil under 5cm is too small for most sorting machines. Bigger is better.'),

  -- BATHROOM & HOUSEHOLD
  ('Toothbrush', 'general', 'household',
    'Mixed plastics, bonded bristles. Sadly general.',
    'TerraCycle runs a free toothbrush recycling programme via Colgate. Worth saving up.',
    'Roughly a billion toothbrushes are thrown away in the UK every year. They''ll outlive us all.'),
  ('Toothpaste tube', 'general', 'household',
    'Mixed plastic and metal layers — most aren''t recyclable.',
    'Some brands (Colgate, Sensodyne) now run free recycling schemes. Check before you bin.',
    'Toothpaste tubes are typically 7 layers of mixed plastic. Engineering miracle. Recycling nightmare.'),
  ('Nappy', 'general', 'household',
    'Always general waste. Always.',
    'Bag them. Bin them. Move on.',
    'A single nappy takes 500 years to break down. The first ones are still out there.'),
  ('Light bulb (LED)', 'general', 'household',
    'NOT in recycling. Most councils have a take-back at the tip.',
    'B&Q, IKEA and Currys have free bulb recycling. Roll the old ones up in newspaper.',
    'A modern LED bulb uses 90% less electricity than the old incandescents and lasts 25 times longer.'),
  ('Batteries', 'general', 'household',
    'NEVER in any kerbside bin. Take to a battery point.',
    'Tesco, Sainsbury''s, B&Q all have battery boxes by the door. They cause bin fires if binned.',
    'Lithium battery fires in bin lorries doubled between 2019 and 2023. Real, present danger.'),

  -- GARDEN
  ('Grass cuttings', 'garden', 'garden',
    'Garden bin or compost.',
    'Don''t bag them. Loose grass = happy compost.',
    'A lawn produces about 200kg of cuttings per year. That''s a lot of free fertiliser.'),
  ('Hedge trimmings', 'garden', 'garden',
    'Garden bin. Cut anything thick into shorter pieces.',
    'Branches over 4cm thick should go to the tip — your bin lorry will thank you.',
    'Hedges support over 80 species of British wildlife. Trim in winter when the birds aren''t nesting.'),
  ('Soil', 'general', 'garden',
    'NOT garden waste in most councils. To the tip with it.',
    'Soil is heavy and fills the bin lorry fast. Most councils ban it from kerbside.',
    'A spadeful of healthy soil contains more living organisms than there are people on Earth.'),
  ('Christmas tree', 'garden', 'garden',
    'Most councils do a January collection. Real trees only.',
    'Ditch the lights, the tinsel, and the angry cat first.',
    'About 8 million real Christmas trees are sold in the UK each year. Composted, they become next year''s mulch.')
)
insert into bindicator_items (council_id, item_name, bin_type, notes, tip, fun_fact, category)
select c.id, i.item_name, i.bin_type, i.notes, i.tip, i.fun_fact, i.category
from items i
cross join bindicator_councils c;
